### ISSUE TITLE
[MSCMPUB-2] publish-scm can fail with many files on windows.

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-scm-publish-plugin#58]
**[Mark Hobson](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mihobson)** opened **[MSCMPUB-2](https://issues.apache.org/jira/browse/MSCMPUB-2?redirect=false)** and commented

Running publish-scm with a large site can cause the command process to fail due to the command line being too long.  For example:

```
[INFO] --- maven-scm-publish-plugin:1.0-beta-1:publish-scm (scm-publish) @ X ---
...
[INFO] Executing: cmd.exe /X /C "git add -- <long list of files>"
```

Results in:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-scm-publish-plugin:1.0-beta-1:publish-scm (scm-publish) on project X: Failed to add new files to SCM: Exception while executing SCM command. Error while executing command. Error while executing process. Cannot run program "cmd.exe" (in directory X): CreateProcess error=206, The filename or extension is too long -> [Help 1]
```

---

**Affects:** 1.0-beta-1

**Issue Links:**
- [SCM-697](https://issues.apache.org/jira/browse/SCM-697) git add fail on windows when a lot of files to add

**Comment by jira-importer** [comment]
**[Olivier Lamy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=olamy)** commented

more a scm issue. or loop on files and add them one by one in the plugin (if windauze is used :-) )

**Comment by jira-importer** [comment]
**[Olivier Lamy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=olamy)** commented

Fixed.
`@Mark` can you test last snapshot ?

**Comment by jira-importer** [comment]
**[Olivier Lamy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=olamy)** commented

more stack trace available ?

**Comment by jira-importer** [comment]
**[Mark Hobson](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mihobson)** commented

Only this if it helps:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-scm-publish-plugin:1.0-SNAPSHOT:publish-scm (scm-publish) on project X: Failed to add new files to SCM: The parameter is already set: binary -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-scm-publish-plugin:1.0-SNAPSHOT:publish-scm (scm-publish) on project X: Failed to add new files to SCM
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:217)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: org.apache.maven.plugin.MojoExecutionException: Failed to add new files to SCM
        at org.apache.maven.plugins.scmpublish.AbstractScmPublishMojo.addFiles(AbstractScmPublishMojo.java:637)
        at org.apache.maven.plugins.scmpublish.ScmPublishPublishScmMojo.scmPublishExecute(ScmPublishPublishScmMojo.java:269)
        at org.apache.maven.plugins.scmpublish.AbstractScmPublishMojo.execute(AbstractScmPublishMojo.java:485)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
        ... 19 more
Caused by: org.apache.maven.scm.ScmException: The parameter is already set: binary
        at org.apache.maven.scm.CommandParameters.setObject(CommandParameters.java:388)
        at org.apache.maven.scm.CommandParameters.setString(CommandParameters.java:95)
        at org.apache.maven.scm.provider.AbstractScmProvider.add(AbstractScmProvider.java:172)
        at org.apache.maven.plugins.scmpublish.AbstractScmPublishMojo.addFiles(AbstractScmPublishMojo.java:623)
        ... 23 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**Comment by jira-importer** [comment]
**[Olivier Lamy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=olamy)** commented

Just deployed a new SNAPSHOT.
Can you try again ?

**Comment by jira-importer** [comment]
**[Mark Hobson](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mihobson)** commented

That fixed it!  I still get a problem after it pushed the site, something to do with staging and aggregate sites, but this is probably a misconfiguration on my part.  I'll take a look when I have a chance.  Thanks for the quick fix!

**Comment by jira-importer** [comment]
**[Olivier Lamy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=olamy)** commented

Must be fixed with last SNAPSHOT of maven-scm-provider-gitexe.
Can you try using -U ?

**Comment by jira-importer** [comment]
**[Mark Hobson](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mihobson)** commented

The NPE has gone away but I'm afraid we still have line length problems :(

```
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-scm-publish-plugin:1.0-SNAPSHOT:publish-scm (default-cli) on project X: Failed to add new files to SCM: The git-add command failed. 'C:\Users\mark\AppData\Local\Temp\git-add9095034289317458180bat' is not recognized as an internal or external command,
operable program or batch file.

        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:217)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: org.apache.maven.plugin.MojoExecutionException: Failed to add new files to SCM: The git-add command failed. 'C:\Users\mark\AppData\Local\Temp\git-add9095034289317458180bat' is not recognized as an internal or external command,
operable program or batch file.

        at org.apache.maven.plugins.scmpublish.AbstractScmPublishMojo.checkScmResult(AbstractScmPublishMojo.java:634)
        at org.apache.maven.plugins.scmpublish.AbstractScmPublishMojo.addFiles(AbstractScmPublishMojo.java:617)
        at org.apache.maven.plugins.scmpublish.ScmPublishPublishScmMojo.scmPublishExecute(ScmPublishPublishScmMojo.java:269)
        at org.apache.maven.plugins.scmpublish.AbstractScmPublishMojo.execute(AbstractScmPublishMojo.java:485)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
        ... 19 more
```

The temporary file is 30646 characters long.  Looks like this exceeds the 8192 limit of cmd.exe:
http://blogs.msdn.com/b/oldnewthing/archive/2003/12/10/56028.aspx

**Comment by jira-importer** [comment]
**[Mark Hobson](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mihobson)** commented

Sure, I'll take a look thanks.

**Comment by jira-importer** [comment]
**[Mark Hobson](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mihobson)** commented

Fixed by SCM-697.
