### ISSUE TITLE
[MSCMPUB-4] Need a working example for GitHub/gh-pages, preferably naturally linked to natural site lifecycle, and multi-module

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-scm-publish-plugin#61]
**[Anthony Whitford](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=awhitford)** opened **[MSCMPUB-4](https://issues.apache.org/jira/browse/MSCMPUB-4?redirect=false)** and commented

I am trying to update my [lombok-maven-plugin](http://awhitford.github.com/lombok.maven/lombok-maven-plugin/index.html) project to use this plugin to publish the project to _Github Pages_.

When I try this command:

```
mvn clean site site:stage-deploy scm-publish:publish-scm
```

which is outlined [here](http://maven.apache.org/plugins/maven-scm-publish-plugin/examples/multi-module-configuration.html), I get this error:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-scm-publish-plugin:1.0-beta-1:publish-scm (default-cli) on project lombok-maven: Unable to checkout from SCM
[ERROR] Provider message:
[ERROR] The git-log command failed.
[ERROR] Command output:
[ERROR] fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
[ERROR] Use '--' to separate paths from revisions
```

(?) Is there a multi-module project in GitHub that uses this plugin that I can use as an example?

This is what I did so far...

```xml
<properties>
  <siteMainDirectory>${user.home}/Sites/lombok.maven</siteMainDirectory>
  <scmPubCheckoutDirectory>${user.home}/site-content-scm/lombok.maven</scmPubCheckoutDirectory>
</properties>
...
<pluginManagement>
  <plugins>
    <plugin>
      <groupId>org.apache.maven.plugins</groupId>
      <artifactId>maven-site-plugin</artifactId>
      <version>3.2</version>
      <configuration>
        <skipDeploy>true</skipDeploy>
        <stagingSiteURL>file://${siteMainDirectory}</stagingSiteURL>
      </configuration>
    </plugin>
...
  </plugins>
</pluginManagement>
...
<plugins>
  <plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-site-plugin</artifactId>
    <executions>
      <execution>
        <id>stage-for-scm-publish</id>
        <phase>post-site</phase>
        <goals>
          <goal>stage</goal>
        </goals>
      </execution>
    </executions>
  </plugin>
  <plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-scm-publish-plugin</artifactId>
    <version>1.0-beta-1</version>
    <configuration>
      <checkoutDirectory>${scmPubCheckoutDirectory}</checkoutDirectory>
      <content>\${siteMainDirectory}</content>
      <tryUpdate>true</tryUpdate>
      <scmBranch>gh-pages</scmBranch>
      <pubScmUrl>scm:git:git@github.com:awhitford/lombok.maven.git</pubScmUrl>
    </configuration>
    <executions>
      <execution>
        <id>scm-publish</id>
        <phase>site-deploy</phase>
        <goals>
          <goal>publish-scm</goal>
        </goals>
      </execution>
    </executions>
  </plugin>
</plugins>
```

Finally, I'm really interested in wiring this up so that when I do a normal `site-deploy` or an implicit one through the release process, it gets published to `gh-pages`   - just like I had working with [wagon-gitsite](https://github.com/awhitford/wagon-gitsite).

---

1 votes, 5 watchers

**Comment by jira-importer** [comment]
**[Anthony Whitford](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=awhitford)** commented

I took a closer look at [tomcat-foo-artifact](https://github.com/olamy/tomcat-foo-artifact/blob/master/pom.xml), and made a couple of adjustments to be consistent...  But now I am getting this problem:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-scm-publish-plugin:1.0-beta-1:publish-scm (default-cli) on project lombok-maven: Failed to checkin files: The git-commit command failed. warning: CRLF will be replaced by LF in checkstyle.rss.
[ERROR] The file will have its original line endings in your working directory.
[ERROR] warning: CRLF will be replaced by LF in lombok-maven-plugin/checkstyle.rss.
[ERROR] The file will have its original line endings in your working directory.
[ERROR] warning: CRLF will be replaced by LF in test-maven-lombok/checkstyle.rss.
[ERROR] The file will have its original line endings in your working directory.
[ERROR] -> [Help 1]
```

Note that I am no longer using the `tryUpdate` feature (which I would think would be more efficient).

(?) Are these _real_ errors?  Or are the warnings being incorrectly translated as an error?

**Comment by jira-importer** [comment]
**[Anthony Whitford](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=awhitford)** commented

I will try...

**Comment by jira-importer** [comment]
**[Anthony Whitford](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=awhitford)** commented

For the **Maven Multi Module Configuration** advice, it mentions this command:

```
mvn -Preporting site site:stage
```

Is the `reporting` profile necessary?  (Because it doesn't seem to exist.)

I am able to stage the site just fine, but the next step:

```
mvn scm-publish:publish-scm
```

is failing for me with:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-scm-publish-plugin:1.0-SNAPSHOT:publish-scm (default-cli) 
on project lombok-maven: Execution default-cli of goal org.apache.maven.plugins:maven-scm-publish-plugin:1.0-SNAPSHOT:
publish-scm failed: The scm url cannot be null. -> [Help 1]
```

The root issue seems to be here:

```
Caused by: java.lang.NullPointerException: The scm url cannot be null.
	at org.apache.maven.scm.manager.AbstractScmManager.makeScmRepository(AbstractScmManager.java:195)
	at org.apache.maven.shared.release.scm.DefaultScmRepositoryConfigurator.getConfiguredRepository(DefaultScmRepositoryConfigurator.java:78)
	at org.apache.maven.shared.release.scm.DefaultScmRepositoryConfigurator.getConfiguredRepository(DefaultScmRepositoryConfigurator.java:67)
```

And the debug information for the plugin is:

```
[DEBUG] Configuring mojo org.apache.maven.plugins:maven-scm-publish-plugin:1.0-SNAPSHOT:publish-scm from plugin realm ClassRealm[plugin>org.apache.maven.plugins:maven-scm-publish-plugin:1.0-SNAPSHOT, parent: sun.misc.Launcher$AppClassLoader@713c817]
[DEBUG] Configuring mojo 'org.apache.maven.plugins:maven-scm-publish-plugin:1.0-SNAPSHOT:publish-scm' with basic configurator -->
[DEBUG]   (f) automaticRemotePathCreation = true
[DEBUG]   (f) basedir = /Users/anthony/Documents/lombok.maven
[DEBUG]   (f) checkinComment = Site checkin for project Maven Plugin for Project Lombok
[DEBUG]   (f) checkoutDirectory = /Users/anthony/Documents/lombok.maven/target/scmpublish-checkout
[DEBUG]   (f) content = /Users/anthony/Documents/lombok.maven/target/staging
[DEBUG]   (f) localCheckout = false
[DEBUG]   (s) pubScmUrl = scm:git:git@github.com:awhitford/lombok.maven.git
[DEBUG]   (f) scmBranch = gh-pages
[DEBUG]   (f) siteOutputEncoding = UTF-8
[DEBUG]   (f) skipDeletedFiles = false
[DEBUG]   (f) tryUpdate = false
[DEBUG]   (f) project = MavenProject: org.projectlombok:lombok-maven:1.12.4.0-SNAPSHOT @ /Users/anthony/Documents/lombok.maven/pom.xml
[DEBUG]   (f) settings = org.apache.maven.execution.SettingsAdapter@dcd88ea
[DEBUG] -- end configuration --
```

_Am I doing something wrong?_

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

I did a small adjustment in [r1562963](http://svn.apache.org/r1562963), which is the only place (other than by plexus DI) where the scmUrl is set. Not sure if this fixes the issue, please give it another try.

**Comment by jira-importer** [comment]
**[Anthony Whitford](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=awhitford)** commented

Awesome!  It looks like it worked:  [lombok.maven](http://awhitford.github.io/lombok.maven/)

**Comment by jira-importer** [comment]
**[Hervé Boutemy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hboutemy)** commented

great!
thank you for your tests that helped us detect a stupid little bug :)

I'll do the 1.0 release shortly: stay tuned!
